apiVersion: v1
kind: Service
metadata:
  name: webapp-service

spec:
  selector:
    app: webapp
    #release: "0-5"
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: LoadBalancer
